### ISSUE TITLE
Question for benchmark

### ISSUE THREAD

**Issue by HanXiaoyou** [SeanChenxy/Hand3DResearch#1]
请问benchmark的结果是从哪里找到的呀？是类似于paperwithcode还是您自己复现跑的结果呢~期待回复

**Comment by SeanChenxy** [comment]
Hi, FreiHAND的精度和curve都来自于官方leaderboard或者原论文。RHD的精度都来源于原论文，部分curve没有开源，我们通过对论文中的figure取点重新plot。这个repo还在不断改良中，所有结果仅做参考，如有错误或敬请指出。

**Comment by HanXiaoyou** [comment]
明白啦，非常感谢~
