### ISSUE TITLE
New researcher asking about the future researching direction

### ISSUE THREAD

**Issue by KunHanKH** [SeanChenxy/Hand3DResearch#3]
Hi, Xingyu, 
I'm a new researcher about the hand. There are quite a lot of areas in the research of hand topic as you list in the repo. As a new researcher, which direction would you recommend going? I checked your blog and found that the pose and mesh estimation have already reached a high level, the next is about the hand-hand or hand-object. Do you still have the same opinion? I'll appreciate any guidance from you. :)

**Comment by SeanChenxy** [comment]
Hi, Kris. Sorry for late reply. In terms of reconstruction, there has been a surge of research interest in human appearance modeling, including beyond-SMPL/MANO geometry and personalized photorealistic texture. This scope has shown strong both academic and commercial potential. Also, the interaction between human/hand and object/scene under physical constrains is still worthy of in-depth exploration.
